import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/contexts/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface UserDetail {
  id: number;
  name: string;
  username: string;
  email: string;
}

async function getData(): Promise<UserDetail> {
  console.log("Call user detail");
  const res = await fetch("https://jsonplaceholder.typicode.com/users/1");
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  // Recommendation: handle errors
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider user={user}>{children}</AuthProvider>
      </body>
    </html>
  );
}
